name: dev-image
description: Custom aurora image with more dev tools.

base-image: ghcr.io/ublue-os/aurora-dx
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/medzik/jetbrains/repo/fedora-%OS_VERSION%/medzik-jetbrains-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/atim/lazygit/repo/fedora-%OS_VERSION%/atim-lazygit-fedora-%OS_VERSION%.repo
    install:
      - rider
      - alacritty
      - lazygit
      - mediawriter
      - gwenview
      - haruna
      - filelight
      - libreoffice
      - dotnet-sdk-8.0
      - btop
      - syncthing
    remove:
      - ptyxis
      - skanpage
      - solaar
  - type: default-flatpaks
    notify: true
    system:
      install:
        - io.github.zen_browser.zen
        - com.bitwarden.desktop
        - it.mijorus.gearlever
        - org.fkoehler.KTailctl
        - io.github.dvlv.boxbuddyrs
        - io.missioncenter.MissionCenter
        - dev.vencord.Vesktop
  - type: signing
  - type: script
    scripts:
      - ohmyposh.sh
      - nodejs.sh

