name: dev-image
description: Custom aurora image with more dev tools.

base-image: ghcr.io/ublue-os/aurora-dx
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/medzik/jetbrains/repo/fedora-%OS_VERSION%/medzik-jetbrains-fedora-%OS_VERSION%.repo
    install:
      - rider
      - alacritty
    remove:
    # none for now

  - type: default-flatpaks
    notify: true
    system:
      install:
        - io.github.zen_browser.zen
        - com.bitwarden.desktop
        - it.mijorus.gearlever
      remove:
      # none for now

  - type: signing

